apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-tmnx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-tmnx
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-tmnx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-tmnx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-tmnx
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-uqum-tenant/dotnet-component/devfile-sample-dotnet60-basic-tmnx@sha256:4522475a7e817e7cae6d42fa7945f049aa64053854d2aabd5c3ae94adb8ba700
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
